# Streamlit secrets for deployment
COHERE_API_KEY = "your-cohere-api-key-here"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "your-smtp-username-here"
SMTP_PASS = "your-smtp-password-here"
FROM_EMAIL = "your-from-email-here"
